const state={metrics:{},reports:[],opportunities:[],contents:[],logs:[],system:null,platforms:[],activeView:'dashboard',pendingPublish:null,deferredInstall:null,navHistory:[],navIndex:-1,scrollPositions:{}};
const qs=(s,p=document)=>p.querySelector(s),qsa=(s,p=document)=>[...p.querySelectorAll(s)];
const api=async(path,options={})=>{const res=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.message||`HTTP ${res.status}`);return data};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=v=>v?new Intl.DateTimeFormat('ar-TN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const labelStatus=s=>({DRAFT:'مسودة',IN_PROGRESS:'قيد العمل',IN_REVIEW:'قيد المراجعة',READY:'جاهز للنشر',PUBLISHED:'تم النشر',ARCHIVED:'مؤرشف',SUCCESS:'نجاح',WARNING:'تحذير',ERROR:'خطأ'}[s]||s);
const platformLabel=p=>({facebook:'Facebook',instagram:'Instagram',tiktok:'TikTok',pinterest:'Pinterest',youtube:'YouTube',x:'X'}[p]||p);

async function loadAll(showToast=false){
  const btn=qs('#refreshBtn');btn.classList.add('spin');
  try{
    const [metrics,reports,opportunities,contents,logs,system]=await Promise.all([
      api('/api/metrics'),api('/api/reports'),api('/api/opportunities'),api('/api/content'),api('/api/logs'),api('/api/system')
    ]);
    Object.assign(state,{metrics,reports,opportunities,contents,logs,system,platforms:system.platforms||[]});
    renderAll();if(showToast)toast('تم تحديث البيانات','success');
  }catch(e){toast(e.message,'error');qs('#systemStatus').textContent='تعذر الاتصال بالخادم';qs('#systemDot').className='warn'}finally{btn.classList.remove('spin')}
}

function renderAll(){renderMetrics();renderLatest();renderReports();renderOpportunities();renderContent();renderLogs();renderIntegrations();renderPlatformChoices();renderSystemStatus()}
function renderMetrics(){
  const m=state.metrics;const items=[
    ['إجمالي المحتوى',m.totalContent||0,'كل الحزم','content','ALL'],['قيد المراجعة',m.IN_REVIEW||0,'تحتاج قرارك','content','IN_REVIEW'],['جاهز للنشر',m.READY||0,'مرّ بالموافقة','content','READY'],['تم النشر',m.PUBLISHED||0,'منشور للعموم','content','PUBLISHED'],
    ['Success',m.success||0,'عمليات ناجحة','logs'],['Warning',m.warning||0,'تحتاج متابعة','logs'],['Error',m.error||0,'أخطاء النشر','logs'],['نسبة النجاح',`${m.publishingSuccessRate||0}%`,'من سجلات النشر','logs']
  ];
  qs('#metricsGrid').innerHTML=items.map(([l,v,n,view,status])=>`<button class="metric-card interactive-card" type="button" data-view-link="${view}" ${status?`data-content-status="${status}"`:''}><div class="metric-label">${l}</div><div class="metric-value">${v}</div><div class="metric-note">${n}</div></button>`).join('');
}
function renderLatest(){const box=qs('#latestContent');const items=[...state.contents].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5);box.classList.toggle('empty-box',!items.length);box.innerHTML=items.length?items.map(c=>`<div class="list-row"><div><strong>${esc(c.title)}</strong><small>${(c.platforms||[]).map(platformLabel).join(' · ')}</small></div><span class="status-chip ${c.status}">${labelStatus(c.status)}</span></div>`).join(''):'لا يوجد محتوى بعد.'}
function renderReports(){const body=qs('#reportsBody');body.innerHTML=state.reports.length?[...state.reports].reverse().map(r=>`<tr><td><button class="table-title-link" data-report-details="${r.id}">${esc(r.title)}</button></td><td>${esc(r.source||'—')}</td><td>${fmtDate(r.createdAt)}</td><td><div class="table-actions"><button class="small-btn" data-report-details="${r.id}">قراءة</button>${safeUrl(r.googleDriveUrl)?`<a class="small-btn drive-button" href="${esc(safeUrl(r.googleDriveUrl))}" target="_blank" rel="noopener noreferrer">فتح في Drive ↗</a>`:`<button class="small-btn" data-archive-report="${r.id}">حفظ في Drive</button>`}<button class="small-btn" data-extract="${r.id}">استخراج الفرص</button></div></td></tr>`).join(''):`<tr><td colspan="4" class="empty-box">أضف أول تقرير لبدء المنظومة.</td></tr>`}
function renderOpportunities(){qs('#opportunityCount').textContent=`${state.opportunities.length} فرصة`;const grid=qs('#opportunityGrid');grid.innerHTML=state.opportunities.length?state.opportunities.map(o=>{const seo=o.semrush;const seoTags=seo?`<div class="platform-tags"><span class="platform-tag">بحث ${Number(seo.searchVolume||0).toLocaleString('ar')}</span>${seo.keywordDifficulty!=null?`<span class="platform-tag">صعوبة ${esc(seo.keywordDifficulty)}</span>`:''}${seo.intents?.length?`<span class="platform-tag">${esc(seo.intents.join(' / '))}</span>`:''}</div>`:'';return `<article class="op-card"><div class="op-head"><h3>${esc(o.title)}</h3><div class="score" style="--score:${Number(o.score?.total||0)}"><b>${Number(o.score?.total||0).toFixed(1)}</b></div></div><p>${esc(o.rationale)}</p>${seoTags}<button class="btn primary" data-create-content="${o.id}">تحويل إلى محتوى</button></article>`}).join(''):`<div class="panel empty-box">لا توجد فرص بعد. استخرجها من التقارير.</div>`}
function renderContent(){const filter=qs('#contentFilter').value;const items=state.contents.filter(c=>filter==='ALL'||c.status===filter).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));const grid=qs('#contentGrid');grid.innerHTML=items.length?items.map(contentCard).join(''):`<div class="panel empty-box">لا يوجد محتوى في هذه الحالة.</div>`}
function contentCard(c){
  const p=c.package||{};let actions=`<button class="small-btn" data-details="${c.id}">التفاصيل</button>`;
  if(!['PUBLISHED','ARCHIVED'].includes(c.status))actions+=`<button class="small-btn" data-assets="${c.id}">إنشاء الأصول</button>`;
  if(c.status==='IN_REVIEW')actions+=`<button class="btn primary" data-approve="${c.id}">اعتماد → READY</button>`;
  if(c.status==='READY')actions+=`<button class="btn danger" data-publish="${c.id}">اعتمد وانشر</button>`;
  if(['DRAFT','IN_PROGRESS'].includes(c.status))actions+=`<button class="btn primary" data-review="${c.id}">إرسال للمراجعة</button>`;
  return `<article class="content-card"><div class="content-card-head"><span class="status-chip ${c.status}">${labelStatus(c.status)}</span><small>v${c.revision}</small></div><h3>${esc(c.title)}</h3><div class="platform-tags">${(c.platforms||[]).map(x=>`<span class="platform-tag">${platformLabel(x)}</span>`).join('')}</div><div class="content-snippet"><b>Hook:</b> ${esc(p.hook||'—')}</div><div class="card-actions">${actions}</div></article>`
}
function renderLogs(){const body=qs('#logsBody');const contentMap=Object.fromEntries(state.contents.map(c=>[c.id,c.title]));body.innerHTML=state.logs.length?[...state.logs].reverse().map(l=>`<tr><td><span class="status-chip ${l.result}">${labelStatus(l.result)}</span></td><td>${platformLabel(l.platform)}</td><td>${esc(contentMap[l.contentId]||l.contentId.slice(0,8))}</td><td>${l.attempt||1}</td><td>${fmtDate(l.timestamp)}</td><td>${l.publicUrl?`<a href="${esc(l.publicUrl)}" target="_blank" rel="noopener">فتح</a>`:'—'}</td></tr>`).join(''):`<tr><td colspan="6" class="empty-box">لا توجد سجلات نشر بعد.</td></tr>`}
function renderIntegrations(){if(!state.system)return;const desc={ChatGPT:'تحليل التقارير وصناعة المحتوى',ClickUp:'المراجعة والحالات وREADY/PUBLISHED',Make:'محرك النشر إلى المنصات','Google Drive':'تخزين الأصول والملفات',Semrush:'الكلمات المفتاحية والطلب',Canva:'التصميم والكاروسيل',HeyGen:'فيديو المقدم الرقمي عبر مسار الأتمتة',Remotion:'فيديوهات متعددة المقاسات 9:16 و16:9 و1:1 و4:5 و2:3 مع دعم العربية وRTL'};const entries=Object.entries(state.system.integrations||{});qs('#integrationGrid').innerHTML=entries.map(([name,on])=>`<article class="integration-card"><div class="top"><h3>${name}</h3><span class="${on?'pill-on':'pill-off'}">${on?'متصل':'يحتاج إعداد'}</span></div><p>${desc[name]||''}</p></article>`).join('');qs('#integrationMini').innerHTML=entries.slice(0,8).map(([n,on])=>`<div class="row"><span>${n}</span><b class="${on?'pill-on':'pill-off'}">${on?'جاهز':'غير مضبوط'}</b></div>`).join('');qs('#publishMode').textContent=state.system.publishMode==='clickup_watch'?'ClickUp Watch → Make':'Make Webhook'}
function renderSystemStatus(){if(!state.system)return;const ready=state.system.integrations?.ClickUp;qs('#systemDot').className=ready?'ok':'warn';qs('#systemStatus').textContent=ready?'النظام جاهز — ClickUp متصل':'التطبيق يعمل — أضف Credentials للتشغيل الحي'}
function renderPlatformChoices(){const host=qs('#platformChoices');host.innerHTML=(state.platforms||[]).map((p,i)=>`<label class="platform-choice"><input type="checkbox" name="platform" value="${esc(p)}" ${i<5?'checked':''}> ${platformLabel(p)}</label>`).join('')}

function openModal(id){qs('#modalBackdrop').classList.add('show');const m=qs(`#${id}`);m.classList.add('show');m.setAttribute('aria-hidden','false')}
function closeModals(){qs('#modalBackdrop').classList.remove('show');qsa('.modal.show').forEach(m=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')})}
const validViews=['dashboard','reports','opportunities','content','logs','integrations'];
function updateNavButtons(){qs('#navBackBtn').disabled=state.navIndex<=0;qs('#navForwardBtn').disabled=state.navIndex<0||state.navIndex>=state.navHistory.length-1}
function switchView(name,{record=true,restoreScroll=false,replace=false}={}){
  if(!validViews.includes(name))name='dashboard';
  const previous=state.activeView;state.scrollPositions[previous]=scrollY;
  if(record&&name!==previous){state.navHistory=state.navHistory.slice(0,state.navIndex+1);state.navHistory.push(name);state.navIndex=state.navHistory.length-1;const url=new URL(location.href);url.searchParams.set('view',name);history.pushState({view:name,navIndex:state.navIndex},'',url)}
  else if(replace){state.navHistory=[name];state.navIndex=0;const url=new URL(location.href);url.searchParams.set('view',name);history.replaceState({view:name,navIndex:0},'',url)}
  state.activeView=name;qsa('.view').forEach(v=>v.classList.remove('active'));qs(`#view-${name}`).classList.add('active');qsa('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const map={dashboard:['لوحة التحكم','متابعة المنظومة من الفكرة حتى النشر'],reports:['التقارير','المصادر اليومية والسابقة'],opportunities:['بنك الفرص','أفضل ما يمكن تحويله إلى محتوى أو منتج'],content:['خط إنتاج المحتوى','المراجعة والأصول والموافقة والنشر'],logs:['سجل النشر','SUCCESS / WARNING / ERROR'],integrations:['التكاملات','حالة الربط مع الأدوات الخارجية']};qs('#pageTitle').textContent=map[name][0];qs('#pageSubtitle').textContent=map[name][1];qs('#sidebar').classList.remove('open');updateNavButtons();requestAnimationFrame(()=>scrollTo({top:restoreScroll?(state.scrollPositions[name]||0):0,behavior:'smooth'}))
}
function navigateHistory(direction){const target=state.navIndex+direction;if(target<0||target>=state.navHistory.length)return;direction<0?history.back():history.forward()}
function toast(msg,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;qs('#toastHost').append(el);setTimeout(()=>el.remove(),4200)}

async function extractOpportunities(id,button){button.disabled=true;button.textContent='جاري التحليل…';try{const out=await api(`/api/reports/${id}/opportunities`,{method:'POST'});toast(`تم استخراج ${out.length} فرصة`,'success');await loadAll();switchView('opportunities')}catch(e){toast(e.message,'error')}finally{button.disabled=false;button.textContent='استخراج الفرص'}}
function startContent(id){const o=state.opportunities.find(x=>x.id===id);qs('#platformOpportunityTitle').textContent=o?.title||'';qs('#platformForm [name=opportunityId]').value=id;openModal('platformModal')}
async function action(id,kind){try{let result;if(kind==='approve')result=await api(`/api/content/${id}/approve`,{method:'POST',body:JSON.stringify({approvedBy:'Ghaith Web Owner'})});if(kind==='review')result=await api(`/api/content/${id}/review`,{method:'POST'});if(kind==='assets')result=await api(`/api/content/${id}/assets`,{method:'POST'});toast(kind==='approve'?'تم الاعتماد وأصبح المحتوى READY':kind==='assets'?'تم إرسال طلب الأصول':'تم الإرسال للمراجعة','success');await loadAll();return result}catch(e){toast(e.message,'error')}}
function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function assetLinks(c){const rows=[...(c.assets||[]).map(a=>({label:`${a.kind}${a.format?` ${a.format}`:''} — ${a.provider||'أصل'}`,url:a.url})),...(c.googleDriveUrls||[]).map((url,i)=>({label:`Google Drive ${i+1}`,url}))];const seen=new Set;const links=rows.filter(x=>safeUrl(x.url)&&!seen.has(x.url)&&seen.add(x.url));return links.length?`<div class="asset-links">${links.map(x=>`<a class="drive-link" href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">${esc(x.label)} ↗</a>`).join('')}</div>`:'<p>لا توجد أصول بعد</p>'}
function showDetails(id){const c=state.contents.find(x=>x.id===id);if(!c)return;qs('#contentModalTitle').textContent=c.title;qs('#contentModalMeta').textContent=`${labelStatus(c.status)} · v${c.revision} · ${(c.platforms||[]).map(platformLabel).join('، ')}`;const p=c.package||{};qs('#contentModalBody').innerHTML=`<div class="detail-body"><div class="detail-grid"><section class="detail-section"><h4>Hook</h4><p>${esc(p.hook||'—')}</p></section><section class="detail-section"><h4>CTA</h4><p>${esc(p.cta||'—')}</p></section></div><section class="detail-section"><h4>Caption</h4><pre>${esc(p.caption||'—')}</pre></section><section class="detail-section"><h4>Script</h4><pre>${esc(p.script||'—')}</pre></section><section class="detail-section"><h4>Image Prompt</h4><pre>${esc(p.imagePrompt||'—')}</pre></section><section class="detail-section"><h4>Video Prompt</h4><pre>${esc(p.videoPrompt||'—')}</pre></section><section class="detail-section"><h4>Keywords</h4><p>${esc((p.keywords||[]).join('، ')||'—')}</p></section><section class="detail-section"><h4>الأصول والروابط</h4>${assetLinks(c)}</section><section class="detail-section"><h4>ClickUp Task ID</h4><p>${esc(c.clickupTaskId||'غير مرتبط بعد')}</p></section></div>`;openModal('contentModal')}
function showReportDetails(id){const r=state.reports.find(x=>x.id===id);if(!r)return;qs('#reportDetailsTitle').textContent=r.title;qs('#reportDetailsMeta').textContent=`${r.source||'دون مصدر'} · ${fmtDate(r.createdAt)}`;qs('#reportDetailsBody').innerHTML=`<div class="detail-body"><section class="detail-section"><h4>نص التقرير</h4><pre class="report-full-text">${esc(r.body||'لا يوجد نص')}</pre></section><div class="form-actions"><button class="btn primary" data-extract="${r.id}">استخراج أفضل الفرص</button></div></div>`;openModal('reportDetailsModal')}
async function archiveReport(id,button){button.disabled=true;button.textContent='جاري الحفظ…';try{await api(`/api/reports/${id}/archive`,{method:'POST'});toast('تم حفظ التقرير الكامل في Drive','success');await loadAll()}catch(e){toast(e.message,'error')}finally{button.disabled=false}}
async function archiveAllReports(){const button=qs('#archiveAllReportsBtn');button.disabled=true;let total=0;try{for(let batch=0;batch<20;batch++){button.textContent=`جاري الحفظ… ${total}`;const result=await api('/api/reports/archive-pending?limit=10',{method:'POST'});total+=(result.archived||[]).length;if(!result.remaining)break}toast(`اكتمل حفظ ${total} تقريرًا في Drive`,'success');await loadAll()}catch(e){toast(`توقف الحفظ بعد ${total}: ${e.message}`,'error')}finally{button.disabled=false;button.textContent='حفظ كل التقارير في Drive'}}
function askPublish(id){const c=state.contents.find(x=>x.id===id);if(!c)return;state.pendingPublish=id;qs('#confirmText').textContent=`سيتم تسليم «${c.title}» للنشر عبر ${state.system?.publishMode==='clickup_watch'?'ClickUp READY ثم سيناريو Make الحالي':'Make Webhook'}.`;openModal('confirmModal')}
async function confirmPublish(){if(!state.pendingPublish)return;const b=qs('#confirmPublishBtn');b.disabled=true;b.textContent='جاري التسليم…';try{const r=await api(`/api/content/${state.pendingPublish}/publish`,{method:'POST'});closeModals();if(r.dispatched)toast('تم التسليم: READY في ClickUp، وMake يمكنه التقاط المهمة','success');else if(r.published)toast('تم النشر بنجاح','success');else toast(r.warning||'تم تنفيذ الطلب');await loadAll()}catch(e){toast(e.message,'error')}finally{b.disabled=false;b.textContent='اعتمد وأرسل للنشر';state.pendingPublish=null}}

qs('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const b=e.submitter;b.disabled=true;try{await api('/api/reports',{method:'POST',body:JSON.stringify({title:f.get('title'),source:f.get('source'),body:f.get('body')})});e.currentTarget.reset();closeModals();toast('تم حفظ التقرير','success');await loadAll();switchView('reports')}catch(err){toast(err.message,'error')}finally{b.disabled=false}});
qs('#platformForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('opportunityId'),platforms=f.getAll('platform');if(!platforms.length)return toast('اختر منصة واحدة على الأقل','error');const b=e.submitter;b.disabled=true;b.textContent='جاري الإنشاء…';try{await api(`/api/opportunities/${id}/content`,{method:'POST',body:JSON.stringify({platforms})});closeModals();toast('تم إنشاء حزمة المحتوى وإرسالها إلى IN REVIEW','success');await loadAll();switchView('content')}catch(err){toast(err.message,'error')}finally{b.disabled=false;b.textContent='إنشاء المحتوى'}});

document.addEventListener('click',e=>{const t=e.target.closest('button,[data-view-link]');if(!t)return;if(t.dataset.view)switchView(t.dataset.view);if(t.dataset.viewLink){switchView(t.dataset.viewLink);if(t.dataset.contentStatus){qs('#contentFilter').value=t.dataset.contentStatus;renderContent()}}if(t.dataset.open)openModal(t.dataset.open);if(t.hasAttribute('data-close'))closeModals();if(t.dataset.reportDetails)showReportDetails(t.dataset.reportDetails);if(t.dataset.archiveReport)archiveReport(t.dataset.archiveReport,t);if(t.dataset.extract)extractOpportunities(t.dataset.extract,t);if(t.dataset.createContent)startContent(t.dataset.createContent);if(t.dataset.details)showDetails(t.dataset.details);if(t.dataset.approve)action(t.dataset.approve,'approve');if(t.dataset.review)action(t.dataset.review,'review');if(t.dataset.assets)action(t.dataset.assets,'assets');if(t.dataset.publish)askPublish(t.dataset.publish)});
qs('#modalBackdrop').addEventListener('click',closeModals);qs('#refreshBtn').addEventListener('click',()=>loadAll(true));qs('#menuBtn').addEventListener('click',()=>qs('#sidebar').classList.toggle('open'));qs('#contentFilter').addEventListener('change',renderContent);qs('#confirmPublishBtn').addEventListener('click',confirmPublish);
qs('#navBackBtn').addEventListener('click',()=>navigateHistory(-1));qs('#navForwardBtn').addEventListener('click',()=>navigateHistory(1));
window.addEventListener('popstate',e=>{const name=e.state?.view||new URLSearchParams(location.search).get('view')||'dashboard';const index=Number(e.state?.navIndex);if(Number.isInteger(index)&&index>=0)state.navIndex=index;switchView(name,{record:false,restoreScroll:true});updateNavButtons()});
qs('#archiveAllReportsBtn').addEventListener('click',archiveAllReports);
qs('#copyEnvBtn').addEventListener('click',async()=>{const text=['OPENAI_API_KEY','CLICKUP_API_TOKEN','CLICKUP_LIST_ID','PUBLISH_MODE','MAKE_WEBHOOK_URL','MAKE_WEBHOOK_SECRET','GOOGLE_DRIVE_ACCESS_TOKEN','GOOGLE_DRIVE_FOLDER_ID','SEMRUSH_API_URL','SEMRUSH_API_KEY','CANVA_AUTOMATION_WEBHOOK_URL','HEYGEN_AUTOMATION_WEBHOOK_URL','SUPPORTED_PLATFORMS'].join('\n');await navigator.clipboard.writeText(text);toast('تم نسخ أسماء الإعدادات','success')});

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;qs('#installBtn').hidden=false});qs('#installBtn').addEventListener('click',async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;qs('#installBtn').hidden=true});
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{
  let reloading=false;
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(reloading||!navigator.serviceWorker.controller)return;
    reloading=true;
    location.reload();
  });
  try{
    const registration=await navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'});
    await registration.update();
  }catch{}
});
async function boot(){await loadAll();const requested=new URLSearchParams(location.search).get('view');switchView(validViews.includes(requested)?requested:'dashboard',{record:false,replace:true})}
setInterval(()=>loadAll(false),30000);boot();
